### ISSUE TITLE
Exception on filed tests

### ISSUE THREAD

**Issue by radzisz** [zixia/gast#13]
I'm using TAP for a few months - good job and many thanks, I benefit a lot.
I look for the feature "rise an exception on filed tests" for the following reasons:
1) Mature GAS script production procedures involve 3ed party stuff (DevOps/ QA) in the script provisioning. As a failed tests can only be detected by examining the Log console, sometimes they claim tests to pass even if it actually fails.
2) Our apps has more then a hundred tests - its not easy to find which one filed if your log includes application logs and mixed with Gast logs...

We could extend options used while creating GasTap with failOnFailedTest option (true/false) and the implantation respectively. Shell I provide a pull request?

**Comment by huan** [comment]
Hi, @radzisz !

It's great to hear from you that you have been benefited a lot from GasT library.

I understand what's your need: throw a GAS exception when the test failed, so that we could detect the test fail more easily instead of check the log output text.

I have a quick check of the TAP protocol, it has a **Bail Out** setting, you might like to have a look at:
1. https://testanything.org/tap-specification.html
1. http://www.node-tap.org/tap-format/

I think we should select a name that follows the TAP protocol(and other common implementations).

And yes, PR is welcome, please! :)

**Comment by radzisz** [comment]
How about baliOutOnFail or giveUpOnFailure?
The bailOut is rather intend for test initialization phase while my case is to giveup on regular test failure.
It also would be fine for me only to signal failure at the and of the tests in more explicit way then only on the logger.
As the alternative we could add a possibility to check number of failures on test object by exposing  values of totalSucc, totalFail, totalSkip - nothe vvalues can only be access by parsing logged text...

**Comment by huan** [comment]
No problem. 

Could you please make a PR and show all you need in the code? Because that will show your design in detail.

And then we will be able to continue discussing based on your PR.

**Comment by huan** [comment]
Close this issue because the PR had been merged.
